### ISSUE TITLE
validate ilcd zip file

### ISSUE THREAD

**Issue by mfastudillo** [sami-m-g/pyilcd#2]
Perhaps this is a trivial suggestion, but I think it would be nice to be able to validate an entire ilcd dataset from the zipfile.

**Comment by sami-m-g** [comment]
Hey, @mfastudillo. Thanks for your suggestion!
I am working on adding validation for directories as well as validation and parsing for ZIP files. Should be done by tomorrow!

**Comment by sami-m-g** [comment]
Validation and parsing for ZIP files and validation for directories have been added in `v6.3.0`.

**Comment by sami-m-g** [comment]
Validation and parsing for ZIP files and validation for directories have been added in `v6.3.0`.
